-- ==========================================
-- VERIFICAR E CONFIGURAR AUTO-INCREMENT NA TABELA EVENTOS
-- ==========================================
-- 
-- Este script verifica se a coluna ID tem auto-increment configurado
-- e adiciona se necessário (sem dar erro se já existir)
--
-- ==========================================

DO $$
BEGIN
    -- Verificar se a coluna já é IDENTITY
    IF NOT EXISTS (
        SELECT 1
        FROM pg_attribute a
        JOIN pg_class c ON a.attrelid = c.oid
        WHERE c.relname = 'eventos'
          AND a.attname = 'id'
          AND a.attidentity != ''
    ) THEN
        -- Se não for IDENTITY, adicionar
        ALTER TABLE public.eventos 
        ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
        
        RAISE NOTICE '✅ Auto-increment adicionado à coluna ID';
    ELSE
        -- Se já for IDENTITY, apenas informar
        RAISE NOTICE '✅ A coluna ID já tem auto-increment configurado!';
    END IF;
END $$;

-- ==========================================
-- VERIFICAR ESTRUTURA FINAL
-- ==========================================

SELECT 
    'eventos' as tabela,
    column_name as coluna,
    data_type as tipo,
    is_identity as "auto_increment?",
    column_default as "valor_padrao"
FROM information_schema.columns
WHERE table_schema = 'public'
  AND table_name = 'eventos'
  AND column_name = 'id';

-- ==========================================
-- FIM DO SCRIPT
-- ==========================================