-- ==========================================
-- VERIFICAR E CORRIGIR TABELA EVENTOS
-- ==========================================
--
-- Execute este script no Supabase SQL Editor para verificar
-- se a tabela eventos está configurada corretamente
--
-- ==========================================

-- 1. VERIFICAR SE A TABELA TEM AUTO-INCREMENT
SELECT column_name, column_default, data_type
FROM information_schema.columns
WHERE table_schema = 'public'
  AND table_name = 'eventos'
  AND column_name = 'id';

-- 2. VERIFICAR SEQUENCE (gerador de IDs)
SELECT 
    schemaname,
    sequencename,
    last_value,
    start_value,
    increment_by
FROM pg_sequences
WHERE sequencename LIKE '%eventos%';

-- 3. VER ESTRUTURA COMPLETA DA TABELA
SELECT 
    column_name,
    data_type,
    column_default,
    is_nullable,
    character_maximum_length
FROM information_schema.columns
WHERE table_schema = 'public'
  AND table_name = 'eventos'
ORDER BY ordinal_position;

-- ==========================================
-- SE A COLUNA ID NÃO TIVER AUTO-INCREMENT, EXECUTE ISTO:
-- ==========================================

-- Opção 1: Se a coluna ID não é serial/identity, converter para IDENTITY
DO $$
BEGIN
    -- Verificar se a coluna já é IDENTITY
    IF NOT EXISTS (
        SELECT 1 
        FROM information_schema.columns 
        WHERE table_name = 'eventos' 
          AND column_name = 'id' 
          AND column_default LIKE 'nextval%'
    ) THEN
        -- Se não tem auto-increment, adicionar
        ALTER TABLE public.eventos 
        ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
        
        RAISE NOTICE '✅ Auto-increment adicionado à coluna ID da tabela eventos';
    ELSE
        RAISE NOTICE '✅ A coluna ID já tem auto-increment configurado';
    END IF;
END $$;

-- ==========================================
-- VERIFICAR DEPOIS DA CORREÇÃO
-- ==========================================

SELECT 
    '✅ VERIFICAÇÃO FINAL' as status,
    column_name,
    column_default,
    data_type
FROM information_schema.columns
WHERE table_schema = 'public'
  AND table_name = 'eventos'
  AND column_name = 'id';

-- ==========================================
-- TESTAR INSERÇÃO (opcional - comentado por segurança)
-- ==========================================

-- Descomente para testar se a inserção funciona sem especificar ID:
/*
INSERT INTO public.eventos (
    nome,
    descricao,
    data_inicio,
    duracao_horas,
    limite_faltas_percentual,
    valor_evento,
    texto_certificado,
    perfil_academico_foco
) VALUES (
    'Teste de Auto-Increment',
    'Evento de teste para verificar auto-increment',
    NOW() + INTERVAL '7 days',
    2,
    25,
    0,
    'Certificado de teste',
    'todos'
) RETURNING id, nome;

-- Se funcionar, você verá o ID gerado automaticamente
-- DELETE o evento de teste depois:
-- DELETE FROM public.eventos WHERE nome = 'Teste de Auto-Increment';
*/

-- ==========================================
-- FIM DO SCRIPT
-- ==========================================
